### ISSUE TITLE
previous_selections_value format

### ISSUE THREAD

**Issue by manjaroblack** [john-adeojo/graph_websearch_agent#3]
When building the prompt for the researcher_agent, the previous_selections_value is being passed to create the prompt in format below. 
![IMG_0177](https://github.com/john-adeojo/graph_websearch_agent/assets/42281273/df196184-6824-4be5-ae94-70c883c105de)
The agent isn’t parsing the HumanMessage content properly. I’m not certain, but perhaps because this is a list of multiple elements the check_for_content() function isn’t parsing the content from the previous_selections_value properly.

**Comment by tradingartofwar** [comment]
I have had so many issues trying to get my Openai api key to work.  I feel like I have tried everything.   double checked key, made a new key, exported in env, double checked env variables in the config file, made sure it is in the right folder, made sure the instructions to it are right.   I'm sure this is because of my inexperience as a developer, but any ideas would be useful.

**Comment by manjaroblack** [comment]
@tradingartofwar your comment is irrelevant to this issue. If you need assistance, you can reach out to the community, but please refrain from adding irrelevant comments to this issue.

> I have had so many issues trying to get my Openai api key to work. I feel like I have tried everything. double checked key, made a new key, exported in env, double checked env variables in the config file, made sure it is in the right folder, made sure the instructions to it are right. I'm sure this is because of my inexperience as a developer, but any ideas would be useful.
